Repository TovahParnes/BirdAI_D7057E, pull requests merged in 2023-12, with the labels that each got.

#262 260 Added health check routine
  src/internal/repositories/repositories.go
Labels: Area: Backend, Final Release

#264 114 Compress images before uploading post
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/home/home-page.component.html
  src/frontend/src/app/home/home-page.component.ts
  src/setup.go
Labels: Area: Frontend, Area: Backend, Final Release

#272 added a fix to the detection model so it dose not crash
  src/AI/detection_model/networking.py
  src/AI/detection_model/yolo.py
Labels: Type: bug
